### ISSUE TITLE
Inconsistent number bases with spinners

### ISSUE THREAD

**Issue by huderlem** [Rangi42/tilemap-studio#1]
Sometimes, the spinners use hexadecimal, and sometimes they use base-10.  This is very confusing.

![image](https://user-images.githubusercontent.com/2229288/70398218-c1053700-19de-11ea-9317-aec901448e62.png)

**Comment by Rangi42** [comment]
You're right, but I'm not quite sure how to address this; tile IDs are consistently in hex, but I'd feel weird inputting the offset or length in hex too. Maybe put a "$" in front of hex spinners?

**Comment by huderlem** [comment]
Adding the `$` prefix would probably be fine.  When it comes to tilesets, my mind is always thinking in hexadecimal, so I personally wouldn't ever want to use base-10 values here.
