### ISSUE TITLE
Sega Mega Drive support

### ISSUE THREAD

**Issue by lab313ru** [Rangi42/tilemap-studio#14]
It would be great to support SMD palettes+tiles formats.

**Comment by Rangi42** [comment]
Never heard of it, what's the format?

**Comment by lab313ru** [comment]
Palette is `00BBGGRR`, where B, G and R are nibbles, so two bytes format per color.
Image format is 4bpp, so every 4 bits are indices in a palette, one byte - two indices. And also 4 palettes at once can be loaded while a game executing.

**Comment by lab313ru** [comment]
https://segaretro.org/Sega_Mega_Drive/Palettes_and_CRAM

**Comment by Rangi42** [comment]
That's a graphics format, not a tilemap format. You can use PNG or BMP images and convert them to 4bpp later.
