### ISSUE TITLE
CSV support

### ISSUE THREAD

**Issue by Sanqui** [Rangi42/tilemap-studio#15]
It would be useful if Tilemap Studio could read tilemaps from CSV.  For example, the Telefang disassembly currently stores tilemaps in a [CSV format](https://github.com/telefang/telefang/blob/master/components/titlelogo/natsume_tmap.csv) ([raw](https://raw.githubusercontent.com/telefang/telefang/master/components/titlelogo/natsume_tmap.csv)).  This may be useful for other projects, including non-console ones.

**Comment by Rangi42** [comment]
The trouble with this is that CSV isn't a *tilemap* format, it's a *file* format. Those numeric values could be plain tile IDs, or RLE-encoded, or tile+attribute pairs, or so on.

That disassembly is using RGBDS, but the readme says "version 0.3.6 or newer". Maybe send them a PR converting to `INCBIN`ned tilemaps and current 0.5.1 syntax.

**Comment by Rangi42** [comment]
The upcoming release will support importing and exporting CSVs, in any format, not just Plain. Such as [tmap.csv+attr.csv](https://github.com/telefang/telefang/tree/master/gfx/screen) pairs:

![image](https://user-images.githubusercontent.com/35663410/130330275-118edb1d-c571-462f-8343-700d1ac06646.png)

![image](https://user-images.githubusercontent.com/35663410/130330277-a1a80ee3-b46b-48a3-bdc6-63559761035f.png)

**Comment by Rangi42** [comment]
@Sanqui [Tilemap Studio 4.0.0](https://github.com/Rangi42/tilemap-studio/releases/tag/v4.0.0) is released with CSV import/export support.

![image](https://user-images.githubusercontent.com/35663410/131273971-ea8f84ad-663f-4984-8faf-2bdddabeb635.png)

**Comment by Sanqui** [comment]
Lovely, thank you for your work!!
