### ISSUE TITLE
x64 version

### ISSUE THREAD

**Issue by kemenaran** [Rangi42/tilemap-studio#16]
I'm trying to use Tilemap-studio on macOS 10.15, using wine. This worked fine on macOS 10.14 (thanks wine!), but now macOS can no longer run 32 bits binary using a 64 bits wine version.

The solution would be to run a x64 version of Tilemap-studio, which should work fine on wine and macOS.

Do you think an x64 version could be provided in Github's Releases?

(Also, thanks for all your work!)

**Comment by Rangi42** [comment]
Maybe in future releases, but I'm not adding x64 builds retroactively. If you can run Visual Studio in Wine, you can try building Tilemap Studio with an x64 configuration (just create it on the x86 one, and make sure to build FLTK also for x64).

**Comment by Rangi42** [comment]
For Windows x86 and x64, the provided 32-bit releases work. For Linux, people build it themselves. I'd rather not provide a second Windows build that's actually for macOS support. See if [Wineskin](https://github.com/Gcenx/WineskinServer) does what you want (it [worked](https://github.com/Rangi42/tilemap-studio/issues/21) for someone using an M1 CPU).

**Comment by kemenaran** [comment]
I eventually got Tilemap Studio 32 bits working on macOS Catalina, using a [build of wine with Crossover patches](https://github.com/Gcenx/homebrew-wine/releases), which supports running 32 bits binaries in a 64 bits process.

Thanks for stating out your position on this, and for your work on Tilemap Studio.

**Comment by Rangi42** [comment]
Thanks, maybe I'll mention that in a "macOS via Wine" support section. (Though noting that I can't test on and don't officially support Apple.)
