### ISSUE TITLE
Add support for saving a tileset

### ISSUE THREAD

**Issue by huderlem** [Rangi42/tilemap-studio#2]
I would expect there to be a `Tileset -> Save Tileset` menu item, but that only exist for the `T`ilemap` menu.  Here, you can see I've constructed a tileset out of two separate images.  I want to save it as a single image, but I can't.

![image](https://user-images.githubusercontent.com/2229288/70398273-3bce5200-19df-11ea-84bb-b53f94843c49.png)

**Comment by Rangi42** [comment]
My eventual plan is to allow exporting and loading ".tileset" files: text files that list multiple images, along with start, offset, and length values. That way you can Add a few different images, export them as a single .tileset, and quickly reload it. However, Tilemap Studio is not meant to edit tileset images, only tilemaps; so I don't want to add any image-saving functionality.

**Comment by Rangi42** [comment]
If you think it would be useful, I could add an Export Tilesets function to save them as one image. Even for single tileset images, that could be worthwhile for turning a \*bpp or \*bpp.lz into a .png.
