### ISSUE TITLE
Examples of creating a GBA map?

### ISSUE THREAD

**Issue by technomancy** [Rangi42/tilemap-studio#22]
I can see in the readme that this project appears to support creating maps for the Gameboy Advance. However, I can't find any documentation or examples about how to use a map created in Tilemap Studio from an actual GBA game codebase.

My best guess is that you would take the binary data saved and run `xdd -i` on it to turn it into a C array which could be included in the codebase, but that only handles the map; are you then on your own for converting the palette and tileset?

**Comment by Rangi42** [comment]
All the tilemap formats are binary data. You can use `xxd -i`, [`INCBIN`](https://github.com/graphitemaster/incbin), `incbin` in an assembly file, or whatever your usual workflow is for including binary files.

Tilesets are PNG or BMP images. You can convert them to 4bpp with [`gbagfx`](https://github.com/pret/pokeemerald/tree/master/tools/gbagfx) or whatever tool you normally use for images.

Image to Tiles supports a lot of palette formats, including JASC, which is what `gbagfx` can convert to binary .gbapal format.

**Comment by technomancy** [comment]
Thanks for the clarification. Should this be added as a note in the documentation somewhere?
