### ISSUE TITLE
Add support for rearranging tiles

### ISSUE THREAD

**Issue by huderlem** [Rangi42/tilemap-studio#3]
I would like to be able to move around tiles in the tileset.  When I move tiles, it should also update the tilemap wherever those tiles are currently used.

**Comment by Rangi42** [comment]
I don't plan to add any functionality for editing tileset images; but if you edit one in Paint or whatever and do Ctrl+R to reload, all of the tilesets you've Loaded/Added will be reloaded. Then if you've swapped tile IDs $AA and $BB, select tile $AA and Alt+click tile any $BB in the tilemap to swap all of them.

**Comment by huderlem** [comment]
Supporting this in the UI would be pretty hairy, in any case.  A lot of the issues I'm dealing with right now are that Pinball loads a full set of 256 tiles from a single image into VRAM starting at `$8800`.  This means the tilemaps generated my `Image to Tiles` are all "flipped" by a value of `0x80`.  I've written a script to accomodate my needs, but maybe there's an opportunity for Tilemap Studio there.

**Comment by Rangi42** [comment]
Yeah, this happens with pokecrystal's gfx/intro/suicune_close.tilemap too.

![image](https://user-images.githubusercontent.com/35663410/70403098-be690880-1a03-11ea-8f24-b40fe3e0ae70.png)

![image](https://user-images.githubusercontent.com/35663410/70403239-464f1280-1a04-11ea-9e71-8013ce2751af.png)

I think that an option to handle this would be pretty awkward (presumably it would make Load Tileset start at $0:80 and wrap around to $0:00? What about bank 1? What about non-GBC formats? Should Add Tileset be affected?) so I hope that the .tileset files mentioned in #2 will be a good solution.

**Comment by Rangi42** [comment]
Closing this since a sufficient resolution is listed in TODO.md ("Auto-Load Tileset").
