### ISSUE TITLE
Feature Request: Snap-to-Grid for Selected Tiles

### ISSUE THREAD

**Issue by JaceDeane** [Rangi42/tilemap-studio#33]
Requesting a snap-to-grid feature when click+dragging selected tiles.

I.e. tiles selected are a 4x4 tile region (like a tree block in pokecrystal), and user drags them to fill a space. The next region of 4x4 tiles on the grid are then overwritten with the selected tiles.

Ala similar to how PolishedMap works when using blocks, except the selected tiles area is modular.
This would be a fine addition to those who use TileMapStudio for mapping. :)

A custom map image has been provided for clarity:
![image_2021-07-23_150033](https://user-images.githubusercontent.com/44044160/126740880-1383b92c-f56b-4615-a9ef-5a6aec4e8eff.png)

**Comment by Rangi42** [comment]
This probably won't be added for a while, if at all; definitely not in the next release. If it were added I'd consider other features relevant to metatiles.

In the meantime, you can at least click to place the whole 4x4 set at once, then release, move the mouse 4 tiles over, click again, etc. I know that's less practical but it should give the same end result.

**Comment by Rangi42** [comment]
The next release will also allow you to click-and-drag over the area with a single unique tile, then Shift+click to fill it with the selected region.

![image](https://user-images.githubusercontent.com/35663410/127237210-e07b83f0-62cc-436c-8f1d-7ae46d7965a3.png)
