### ISSUE TITLE
Undo Functionality Bug

### ISSUE THREAD

**Issue by JaceDeane** [Rangi42/tilemap-studio#39]
Placing a single tile (grouped selection or singular) does not flag the undo button or key shortcuts to be able to reversed.
Only after placing a second does this flag trigger, however the history of actions seems to still be recording, and once another tile is placed, the entire catalogue of placements is able to be undone.

**Comment by Rangi42** [comment]
Note for later: in `change_tile_cb` try moving the `update_active_controls` call *after* the different click handlers when `Fl::event_button() == FL_LEFT_MOUSE`. Also consider factoring out the Undo/Redo update into its own method.
