### ISSUE TITLE
Shortcuts for Adding Modular Selections Directly to Clipboard

### ISSUE THREAD

**Issue by JaceDeane** [Rangi42/tilemap-studio#41]
Ctrl+C directly copying either the selection or the full map (after Ctrl+A to select all) to the clipboard as a shortcut instead of having to go to the export print options button.
Although Ctrl+P + Ctrl+C is a quicker method of this, being able to directly add whatever selection is highlighted to the clipboard would be considerably useful

**Comment by Rangi42** [comment]
Ctrl+C to copy the selected tilemap area to the clipboard, using the current grid/rainbow/palette settings, would make sense. Then Ctrl+A Ctrl+C would copy the whole tilemap without going through the Print dialog.
