### ISSUE TITLE
Add TurboGraphix16/PCEngine support as well as Supergraphix

### ISSUE THREAD

**Issue by TheRealHamtaro126** [Rangi42/tilemap-studio#61]
Can you please add the Turbographix16/PC-Engine format (1-Layer format, 16-color, No tile flip or background priority) and SuperGraphix format (2 layer  and some priority) to the program? You got SNES and GBA, why not these? and no-one had made any PCE nametable/tilemap editors out there right now as of typing this!

Good luck and thanks!

**Comment by Rangi42** [comment]
I'm not familiar with those. Can you link to some documentation on just what data encoding is expected for them? Also, it's unlikely to ever support multi-layer formats, so no SuperGraphix.

**Comment by TheRealHamtaro126** [comment]
https://www.romhacking.net/documents/301/
https://www.romhacking.net/documents/302/

These documents cover the VDP and the formats to an extent where it is humanly readable. Please check out Charles MacDonald's documentation as it serves as the basis for technical info and development!!!

**Comment by Rangi42** [comment]
https://www.chibiakumas.com/6502/pcengine.php has swhat I was looking for:

> The top 4 bits pppp define a 16 color palette number from 0-15... The remaining 12 bits nnnn nnnnnnnn define the tile number

(Although 12 bits can cover 4,096 different tile indexes, only the first 2,048 are supported.)

> We ALWAYS write data to the graphics system registers in HL byte pairs... Little Endian, so low byte first.

(So output a single file whose bytes are `nnnn'nnnn pppp'nnnn nnnn'nnnn pppp'nnnn etc`; the format supports palettes but not flipping.)

**Comment by Rangi42** [comment]
@TheRealHamtaro126 I've just committed Tilemap Studio support for the TurboGrafx-16/PC-Engine. The format sounds pretty simple, but I don't know the TG16 community and haven't tested it on any actual game files. I'd appreciate your help with testing this out and verifying that it fits your needs. It's not released yet, but try building Tilemap Studio from master, or ask me to send a built prerelease copy.
